core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views


app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('view_joke/', views.view_joke, name='view_joke'),
    path('view_joke/<slug:joke_id>/', views.view_joke, name='view_joke'),
    path('rate/<slug:joke_id>/', views.rate, name='rate'),
]

humorgenome/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Joke(models.Model):
    joke_id = models.CharField(primary_key=True, max_length=6)
    title = models.CharField(max_length=500)
    body = models.CharField(max_length=2000)
    ups = models.IntegerField()
    downs = models.IntegerField()
    created_at = models.DateTimeField(editable=False, default=timezone.now)

    class Meta:
        db_table = 'reddit_jokes' ### Reddit crawler inserts jokes into this table

core/views.py
from django.contrib.auth import login, authenticate, logout as logout_auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .models import Joke

import random


def index(request):
    return render(request, 'core/index.html')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('core:view_joke')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

def logout(request):
    logout_auth(request)
    return redirect('core:index')

@login_required
def view_joke(request, joke_id=None):
    if joke_id == None: ### get a random joke_id
        ids = Joke.objects.values_list('joke_id', flat=True)
        joke_id = random.choice(ids)
    joke = get_object_or_404(Joke, pk=joke_id)
    context = {
        'joke': joke,
    }
    return render(request, 'core/view_joke.html', context)

@login_required
def rate(request, joke_id):
    return HttpResponse('You\'re voting on joke {}. Congrats.'.format(joke_id))

core/templates/core/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Humor Genome</title>
    </head>
    <body>
        <div id="headerContainer">
            <div id="div1">
                <a href="/">Humor Genome Project</a>    
            </div>
            <div id="div2">
                {% if user.is_authenticated %}
                    <a href="/logout/">log out</a>
                {% else %}
                    <a href="/login/">log in</a>
                {% endif %}
            </div>

            {% if not user.is_authenticated %}
                <div id="div3">
                    <a href="/signup/">sign up</a>
                </div>
            {% endif %}
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
This is the home page~
{% endblock %}

core/templates/core/view_joke.html
{% extends 'core/base.html' %}

{% block content %}
<h1>{{ joke.title }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'core:rate' joke.joke_id %}" method="post">
	{% csrf_token %}
	<p>{{ joke.body }}</p>

	<input type="radio" name="rating" id="1" value="1" />
	<label for="1">Not funny</label><br/>

	<input type="radio" name="rating" id="2" value="2" />
	<label for="2">Barely funny</label><br/>

	<input type="radio" name="rating" id="3" value="3" />
	<label for="3">Decently funny</label><br/>

	<input type="radio" name="rating" id="4" value="4" />
	<label for="4">Very funny</label><br/>

	<input type="radio" name="rating" id="5" value="5" />
	<label for="5">Absolutely hilarious</label><br/>
	<br/>
<input type="submit" value="Rate" />
</form>
{% endblock %}